DATA:
  TRAIN:
    IMG_DIR: 'datasets/mscoco/val2014'
    LAB_DIR: 'datasets/mscoco/annotations/instances_val2014.json'

  TEST:
    KITTI_DIR: "datasets/KITTI/mask_samples"
    BDD100K_DIR: "datasets/bdd100k/images"

DETECTOR:
  NAME: "faster_rcnn"
  INPUT_SIZE: [640, 640]
  BATCH_SIZE: 1

ATTACKER:
  TYPE: "HA"
  DOUBLE_APPLY: False
  EPOCH: 20
  DECAY_EPOCH: 4
  TRAIN_BATCH:
  REPEAT: 20
  EVAL_BATCH: 1600
  LR: 0.01
  STEP_LR: 0.3
  MOMENTUM: 0.9

  ALPHA: 5
  BETA: 0.000002
  CETA: 0.003
  DELTA: 0.1
  TARGET_LABEL: 'stop sign'  # eight attack labels ['person', 'bicycle', 'car', 'motorcycle', 'bus', 'truck', 'traffic light', 'stop sign']

  PATCH:
    WIDTH: 48
    HEIGHT: 48
    CONTENT: "assets/stop.png"
    EOT: True
    SCALE: 0.2
    ANGLE: 0.1

EVAL:
  SCALE_EVAL: 0.24
  ANGLE_EVAL: 0.1
